In [1]:
import pandas as pd
import tools_vk
df = pd.read_csv('result1.csv')

In [2]:
df.head()

,index,id,from_id,owner_id,date,marked_as_ads,post_type,text,attachments,is_favorite,...,comments.count,comments.can_post,comments.groups_can_post,likes.count,likes.user_likes,likes.can_like,likes.can_publish,reposts.count,reposts.user_reposted,views.count
0,0,186828,-66669811,-66669811,1625394037,0,post,"Яна работала в таможне, мечтала стать актрисои...","[{'type': 'photo', 'photo': {'album_id': -7, '...",False,...,0,1,True,14,0,1,1,7,0,9766
1,1,186742,-66669811,-66669811,1625306222,0,post,На днях завершился главный международный фес...,"[{'type': 'photo', 'photo': {'album_id': -7, '...",False,...,0,1,True,10,0,1,1,3,0,12144
2,2,186619,-66669811,-66669811,1625245810,0,post,Год назад Александр Воронин создал проект по д...,"[{'type': 'link', 'link': {'url': 'https://m.v...",False,...,12,1,True,29,0,1,1,20,0,14669